# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ecf7af60b707d4e8ad80d0642344c05db37dee2e5c8f7e2563c6c7e81ee718ea8b1b567b89db39772c02f0b1ad9b8158f8944776dba132fd16a2cb122421aa9

test:
  secret_key_base: 548e83356d6a89c1f3426c3e12c171ce7158fb827ddfcafbcea776f69f320a0a21287bde0dcd7e23ca01ecad1c71ea532a1a2d4459dd71da4d3dc8bd24c76831

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0006818a4876c5cf164afd4b543ff8c44337a46631f63d19a476a7c7cad2b28ad5fac7ade0585575913e428b9874605593f5d73b3d102b1b1f7c6fd7e719af45
